name: CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [$default-branch]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
      - name: NPM Install
        if: steps.compile.outputs.cache-hit != true
        run: npm ci
      - name: Lint files
        run: npm run lint
        env:
          CI: 'true'

  prettier:
    name: Prettier
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
      - name: Prettier
        run: npx prettier --check .
        env:
          CI: true

  compile:
    name: Compile TypeScript
    needs: [lint, prettier]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
      - name: NPM Install
        if: steps.compile.outputs.cache-hit != true
        run: npm ci
      - name: Create config file
        run: |
          touch src/config.json
          cat > src/config.json << EOF
          ${{ secrets.JSON_CONFIG }}
          EOF
      - name: Compile TypeScript
        run: npm run build
        env:
          CI: 'true'
