name: CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - 'master'
      - 'dev'
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - 'master'
      - 'dev'
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
      - name: Restore npm cache
        uses: actions/cache@v2.1.7
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dev dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
        env:
          CI: 'true'

  prettier:
    name: Prettier
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
      - name: Restore npm cache
        uses: actions/cache@v2.1.7
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Prettier
        run: npx prettier --check .
        env:
          CI: true

  compile:
    name: Compile TypeScript
    needs: [lint, prettier]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node 16
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
      - name: Restore npm cache
        uses: actions/cache@v2.1.7
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: NPM Install
        run: npm ci
      - name: Compile TypeScript
        run: npm run build
        env:
          CI: 'true'
